use_field_init_shorthand = true
use_try_shorthand = true
# imports_granularity = "Item"
# imports_granularity = "Module"
imports_granularity = "Crate"
reorder_imports = true
fn_args_layout = "Compressed"
fn_single_line = true
format_macro_matchers = true
format_strings = true
# imports_indent = "Visual"
# indent_style = "Visual"
match_arm_leading_pipes = "Always"
max_width = 110
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
struct_field_align_threshold = 20
tab_spaces = 2
use_small_heuristics = "Max"
where_single_line = true
wrap_comments = true
comment_width = 110
# force_multiline_blocks = false
